In [19]:
# Load the library with the iris dataset
from sklearn.datasets import load_iris

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

# Set random seed
np.random.seed(0)

In [21]:
# Create an object called iris with the iris data
raw = pd.read_csv('../../clean_data/r_data_18_35_55.csv')

# Create a dataframe with the four feature variables
df = pd.DataFrame(raw)

# View the top 5 rows
df.head()

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game
0,1,0.599194,1.000000,1.0,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355
1,1,0.413265,0.755102,1.0,0.676020,0.936224,0.946429,0.280612,0.729592,0.658163
2,1,0.690476,0.712121,1.0,0.670996,0.942641,0.984848,0.428571,0.642857,0.601732
3,1,0.569312,0.803175,1.0,0.784656,0.981481,0.962963,0.358201,0.671958,0.640212
4,1,0.690476,0.828571,1.0,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571

In [3]:
# Create a new column that for each row, generates a random number between 0 and 1, and
# if that value is less than or equal to .75, then sets the value of that cell as True
# and false otherwise. This is a quick and dirty way of randomly assigning some rows to
# be used as the training data and some as the test data.

df['is_train'] = np.random.uniform(0, 1, len(df)) <= .70

# View the top 5 rows
df.head()

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game,is_train
0,1,0.599194,1.000000,1.0,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355,True
1,1,0.413265,0.755102,1.0,0.676020,0.936224,0.946429,0.280612,0.729592,0.658163,False
2,1,0.690476,0.712121,1.0,0.670996,0.942641,0.984848,0.428571,0.642857,0.601732,True
3,1,0.569312,0.803175,1.0,0.784656,0.981481,0.962963,0.358201,0.671958,0.640212,True
4,1,0.690476,0.828571,1.0,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571,True

In [4]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [5]:
train

,age_label,all_live,magazine,movie_goers,radio,social_media,supermarket,tablet_owner,tv,video_game,is_train
0,1,0.599194,1.000000,1.000000,0.661694,0.942742,0.971371,0.173387,0.745968,0.719355,True
2,1,0.690476,0.712121,1.000000,0.670996,0.942641,0.984848,0.428571,0.642857,0.601732,True
3,1,0.569312,0.803175,1.000000,0.784656,0.981481,0.962963,0.358201,0.671958,0.640212,True
4,1,0.690476,0.828571,1.000000,0.690476,1.000000,0.966667,0.342857,0.861905,0.928571,True
5,1,0.479855,0.973543,1.000000,0.800161,0.930432,1.000000,0.269272,0.817754,0.677814,True
6,1,0.507843,0.793464,1.000000,0.819935,0.979085,0.990196,0.473856,0.833987,0.676797,True
9,1,0.400470,0.612069,1.000000,0.726489,1.000000,0.937304,0.611285,0.560345,0.948276,True
11,2,0.556277,0.861472,1.000000,0.770996,0.896970,0.987013,0.498701,0.861905,0.613853,True
12,2,0.683454,0.794423,1.000000,0.793356,0.925452,1.000000,0.541400,0.819676,0.544174,True
14,2,0.530000,0.781429,1.000000,0.846429,0.982143,1.000000,0.685714,0.942143,1.000000,True
15,2,0.548345,0.975248,1.000000,0.815053,0.814279,0.990099,0.342280,0.959623,0.395653,True
16,2,0.552372,0.896166,1.000000,0.813580,0.837167,0.982391,0.379012,0.929565,0.395906,True
22,3,0.640503,0.872636,1.000000,0.778967,0.711066,0.984653,0.388436,0.969306,0.233549,True
24,3,0.460526,0.911184,1.000000,0.837171,0.858553,1.000000,0.590461,0.942434,0.800987,True
25,1,0.620315,0.963169,1.000000,0.677694,0.964849,0.939132,0.321272,0.839752,0.683122,True
26,1,0.656587,0.825129,1.000000,0.694562,0.975152,0.981481,0.328762,0.822199,0.641116,True
28,1,0.619048,0.776760,1.000000,0.692093,0.979731,0.974523,0.467724,0.794001,0.622357,True
29,1,0.627778,0.801852,1.000000,0.714815,1.000000,0.948148,0.540741,0.722222,0.966667,True
30,1,0.573871,0.955433,1.000000,0.677656,0.927350,0.963980,0.392552,0.873626,0.543346,True
32,1,0.966043,1.000000,0.973396,0.778877,0.787968,0.476203,0.731952,0.784492,0.587567,True
33,1,0.657475,0.871176,1.000000,0.749505,0.865317,0.981818,0.460276,0.839552,0.334339,True
34,1,0.647969,0.760155,1.000000,0.669246,0.989362,0.989362,0.572776,0.790619,0.954545,True
35,2,0.595878,0.947901,1.000000,0.785074,0.879672,0.992063,0.470430,0.921531,0.551075,True
36,2,0.607225,0.830481,1.000000,0.793120,0.961323,0.990866,0.548634,0.902485,0.559908,True
37,2,0.940542,1.000000,1.000000,0.775977,0.774968,0.592497,0.633985,0.916456,0.544893,True
39,2,0.511781,0.864865,1.000000,0.750866,0.948025,0.948025,0.617117,0.881150,0.934511,True
40,2,0.587464,0.956820,1.000000,0.823462,0.805573,0.985538,0.329785,0.887726,0.369355,True
41,2,0.568769,0.882075,1.000000,0.824230,0.818603,0.986180,0.424446,0.912198,0.374048,True
42,2,0.898772,1.000000,0.991404,0.922105,0.817193,0.564211,0.699298,0.924035,0.359474,True
43,2,0.573171,0.695122,1.000000,0.591463,0.975610,0.975610,0.371951,0.768293,0.835366,True
...,...,...,...,...,...,...,...,...,...,...,...
129,1,0.532609,0.617754,1.013889,0.690821,0.972222,0.964372,0.393720,0.631643,1.000000,True
130,1,0.464765,0.975214,1.000000,0.801441,0.888194,0.976243,0.354751,0.849985,0.617373,True
131,1,0.496834,0.750796,1.000000,0.807830,0.947419,0.976300,0.454634,0.827097,0.579447,True
132,1,0.721984,0.714152,1.000000,0.815169,0.929542,0.993506,0.463449,0.808676,0.502176,True
133,1,0.474020,0.751961,1.000000,0.774265,0.952696,1.000000,0.444118,0.746569,0.456373,True
134,1,0.538219,0.684081,1.065217,0.740884,1.041024,1.057153,0.617111,0.811360,1.000000,True
135,2,0.465619,0.949852,1.000000,0.847336,0.889287,0.996528,0.399362,0.932491,0.553905,True
136,2,0.458927,0.804887,1.000000,0.777132,0.878777,0.977946,0.500639,0.890179,0.482114,True
137,2,0.700078,0.750861,1.000000,0.784194,0.945540,1.000000,0.548905,0.827543,0.498670,True
138,2,0.486310,0.715476,1.000000,0.800992,0.950992,0.993056,0.561706,0.855159,0.447421,True
139,2,0.581189,0.767157,1.072304,0.827512,1.027267,1.062500,0.684743,0.849265,1.000000,True
141,2,0.493294,0.859059,1.000000,0.832588,0.830000,0.985059,0.448941,0.919647,0.287529,True
142,2,0.694787,0.815271,1.000000,0.831486,0.875205,0.995690,0.492406,0.907635,0.294951,True
146,3,0.459495,0.916145,1.000000,0.727366,0.649840,0.995588,0.305914,0.961861,0.181074,True
150,1,0.557918,0.972727,1.000000,0.628592,0.947507,0.972727,0.322874,0.784018,0.648974,True
152,1,0.780405,0.691528,1.000000,0.589397,0.945946,0.963358,0.269491,0.743503,0.632277,True
153,1,0.671794,0.780536,1.000000,0.696924,0.979592,0.992537,0.404813,0.714590,0.492690,True
154,1,0.427602,0.825792,1.000000,0.542986,0.970588,1.000000,0.416290,0.805430,1.000000,True
157,1,0.765625,0.759259,1.000000,0.734375,0.964120,1.000000,0.515046,0.827546,0.569155,True
158,1,0.591944,0.788077,1.000000,0.778840,0.989796,1.000000,0.570892,0.817723,0.583459,True
159,1,0.597410,0.747185,1.000000,0.719032,0.972973,1.000000,0.569257,0.698198,0.979167,True
160,2,0.519734,0.989247,1.000000,0.806578,0.872106,0.988235,0.362113,0.887919,0.599241,True
161,2,0.547559,0.839186,1.000000,0.820837,0.859854,0.979331,0.499367,0.874829,0.572973,True
166,2,0.578626,0.869466,1.000000,0.784553,0.843062,1.000000,0.404670,0.889178,0.391154,True
167,2,0.652049,0.828160,1.000000,0.829666,0.873217,0.992063,0.565803,0.876432,0.419932,True
169,2,0.576923,0.836538,1.000000,0.836538,0.907967,0.982143,0.648352,0.851648,0.759615,True
170,3,0.462782,0.947654,1.000000,0.722623,0.627952,0.984775,0.227731,0.931388,0.142430,True
171,3,0.438301,0.953907,1.000000,0.737030,0.677553,0.990854,0.345959,0.908330,0.193313,True
172,3,0.611968,0.919125,1.000000,0.779305,0.725053,0.995614,0.390854,0.937870,0.194854,True
173,3,0.470451,0.910468,1.000000,0.770285,0.683633,0.983772,0.474495,0.937718,0.178759,True

In [6]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 127
Number of observations in the test data: 48

In [7]:
# Create a list of the feature column's names
features = df.columns[1:]

# View features
features

Index(['all_live', 'magazine', 'movie_goers', 'radio', 'social_media',
       'supermarket', 'tablet_owner', 'tv', 'video_game', 'is_train'],
      dtype='object')

In [8]:
y = np.array(train.age_label)
y

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64)

In [9]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[['tv','social_media','radio','video_game','tablet_owner']], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [10]:
test[['tv','social_media','radio','video_game','tablet_owner']].head()

          tv  social_media     radio  video_game  tablet_owner
1   0.729592      0.936224  0.676020    0.658163      0.280612
7   0.736972      0.990566  0.733491    0.641734      0.524034
8   0.754290      0.955556  0.760619    0.626160      0.449930
10  0.913359      0.855954  0.790440    0.610222      0.357341
13  0.847826      0.931159  0.826087    0.572464      0.605072

In [11]:
# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
preds = clf.predict(test[['tv','social_media','radio','video_game','tablet_owner']])

In [12]:
clf.predict_proba(test[['tv','social_media','radio','video_game','tablet_owner']])[0:5]

array([[ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ],
       [ 0.1,  0.9,  0. ],
       [ 0.3,  0.7,  0. ]])

In [13]:
pd.crosstab(test['age_label'], preds, rownames=['Actual Generation'], colnames=['Predicted Generation'])

Predicted Generation   1   2   3
Actual Generation
1                     12   0   0
2                      1  21   0
3                      0   0  14

In [14]:
test_array = [0.75,0.90,0.5,0.6,0.5]
pd.DataFrame(np.array([0.75,0.90,0.5,0.6,0.5]).reshape(1,5),columns=['tv','social_media','radio','video_game','tablet_owner'])

     tv  social_media  radio  video_game  tablet_owner
0  0.75           0.9    0.5         0.6           0.5

In [15]:
TV = float(input('TV: '))
social_media = float(input('social media: '))
radio = float(input('radio: '))
video_game = float(input('video_game: '))
tablet_owner = float(input("tablet_owner: "))

TV: 0.75
social media: 0.9
radio: 0.5
video_game: 0.6
tablet_owner: 0.5

In [16]:
testing_df = pd.DataFrame(np.array([TV,social_media,radio,video_game,tablet_owner]).reshape(1,5),columns=['tv','social_media','radio','video_game','tablet_owner'])
print('Chosen Levels: \ntv: {}\nsocial_media: {}\
        \nradio: {}\nvideo_game: {}\ntablet_owner: {}\
        \nPredicted Class:{}'.format(TV,social_media,radio,video_game,tablet_owner,clf.predict(testing_df)[0]))

Chosen Levels:
tv: 0.75
social_media: 0.9
radio: 0.5
video_game: 0.6
tablet_owner: 0.5
Predicted Class:1

In [17]:
from sklearn.externals import joblib
# export model object as pickle file
joblib.dump(clf, 'prob_model_RF.pkl')

['prob_model_RF.pkl']

In [18]:
# import pickle
# import math
# object_pi = math.pi
# file_pi = open('filename_pi.obj', 'w')
# pickle.dump(object_pi, file_pi)